### ISSUE TITLE
Can't resume when gdm3 is running under wayland

### ISSUE THREAD

**Issue by nailfarmer** [nailfarmer/debian-luks-suspend#1]
On resume from suspend, gdm3 wrests control away from cryptsetup and brings the user to the gdm3 login screen.  This prevents the user from unlocking the encrypted volume.

As a workaround, for those who wish to run gdm3, please use gdm3 under xorg by adding 

`WaylandEnable=false`

to

`/etc/gdm3/daemon/conf`

**Comment by t2d** [comment]
I have investigated the issue and opened a bug report upstream
https://gitlab.gnome.org/GNOME/gdm/issues/527

**Comment by nailfarmer** [comment]
Thanks for investigating the issue and reporting upstream, @t2d, much appreciated.

**Comment by nailfarmer** [comment]
I think I've been able to work around this by using loginctl to explicitly lock the session from inside the virtual terminal environment.  Please let me know if you encounter any issues!
